// 9:16 prompts (Reel vertical)
export const NECKLACE_PREMIUM_PROMPT = `Place the necklace centered on a clean, minimal warm cream background with a soft neutral beige tone. The background should be smooth and uniform, with no visible texture or props. Use diffused soft studio lighting with very gentle shadows and a subtle floating shadow directly beneath the pendant to create a natural suspended effect. The color grading should be warm, slightly muted, low saturation, and evenly balanced. Keep the composition symmetrical, centered, and elegant. Ensure the product appears professionally staged, perfectly aligned, sharp, and high-end e-commerce ready. Maintain accurate colors, realistic reflections on the metal, and natural proportions. Ultra realistic, No Text, No Logo, No Price, No Watermark, high resolution, luxury minimal aesthetic.`;

export const NECKLACE_MODEL_PROMPT = `Pon el producto en una persona modelo como para lucirlo en un e-commerce`;

// 1:1 prompts (Post cuadrado)
export const NECKLACE_PREMIUM_PROMPT_SQUARE = `Minimalist luxury jewelry product background, soft warm beige gradient backdrop, smooth studio lighting, perfectly centered composition, product placed in the exact center of the frame, symmetrical balance, subtle natural shadow directly beneath the product, clean high-end e-commerce aesthetic, soft diffused light, no distractions, no props, no text, matte neutral background texture, sharp focus, ultra high resolution, professional product photography, square format, 1:1 aspect ratio`;

export const NECKLACE_MODEL_PROMPT_SQUARE = `Place the provided necklace naturally hanging on the neck of a female model. The necklace must remain identical in design, color, texture, and proportions to the original product image. Center the necklace perfectly in the frame. The model should be facing forward with a neutral expression. Minimalist luxury aesthetic. Soft warm beige studio background with smooth gradient. Clean styling, natural makeup, neutral clothing (beige or off-white). Soft diffused studio lighting, subtle natural shadows. High-end jewelry photography style. Sharp focus on the necklace. Professional e-commerce look. Square format, 1:1 aspect ratio.`;
